src/Recast.WebApp/Controllers/FeedsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Recast.WebApp.Models;
using Recast.WebApp.Models.Entities;
using Recast.WebApp.Models.ViewModel;
using Recast.XmlFeed;

namespace Recast.WebApp.Controllers;

public class FeedsController : Controller
{
    private readonly Feeds feeds;
    private readonly Posts posts;
    private readonly IMapper mapper;

    public FeedsController(Feeds feeds, Posts posts, IMapper mapper)
    {
        this.feeds = feeds ?? throw new ArgumentNullException(nameof(feeds));
        this.posts = posts ?? throw new ArgumentNullException(nameof(posts));
        this.mapper = mapper;
    }

    [HttpGet]
    public ActionResult New() => View(new FeedViewModel());

    [HttpPost]
    public ActionResult New(FeedViewModel feedViewModel)
    {
        if (!ModelState.IsValid)
            return View(feedViewModel);
        var feed = new Feed(feedViewModel.UserName, feedViewModel.FeedName);

        var created = feeds.Insert(feed);
        if (created)
        {
            return RedirectToRoute("ViewFeed", new { userName = feedViewModel.UserName, feedName = feedViewModel.FeedName });
        }
        ViewBag.IsDuplicate = true;
        return View(feedViewModel);
    }

    public async Task<ActionResult> ViewFeed([FromServices] PostDeletionUsers usersRequiringKey, string userName, string feedName)
    {
        ViewBag.UserName = userName;
        ViewBag.FeedName = feedName;
        var feed = await feeds.GetAsync(userName, feedName);
        if (feed == null)
            return View();
        var feedPosts = await posts.GetForFeed(feed);
        ViewBag.Posts = mapper.Map<IEnumerable<PostViewModel>>(feedPosts);
        ViewBag.CantDelete = usersRequiringKey.Users.Any(u => u == userName);
        return View(feed);
    }

    [HttpGet]
    public ActionResult AddPost([FromServices] PostDeletionUsers usersRequiringKey, string userName, string feedName)
    {
        ViewBag.NeedsKey = usersRequiringKey.Users.Any(u => u == userName);
        return View(new PostViewModel { UserName = userName, FeedName = feedName, PublishDate = DateTime.Now, SongLink = "http://" });
    }

    [HttpPost]
    public ActionResult AddPost([FromServices] PostDeletionUsers usersRequiringKey, [FromServices] PostDeletionKey creationKey, PostViewModel postView, string key)
    {
        var requiresKey = usersRequiringKey.Users.Any(u => u == postView.UserName);
        if (!ModelState.IsValid || requiresKey && creationKey.Key != key)
        {
            ViewBag.NeedsKey = usersRequiringKey.Users.Any(u => u == postView.UserName);
            ViewBag.Key = key;
            return View(postView);
        }

        var post = mapper.Map<Post>(postView);
        posts.Insert(post);

        return RedirectToRoute("ViewFeed", new { userName = post.GetUserName(), feedName = post.GetFeedName() });
    }
    [HttpGet]
    public ActionResult GoToFeed() => View();
    [HttpPost]
    public ActionResult GoToFeed(FeedViewModel feedViewModel) => !ModelState.IsValid
            ? View(feedViewModel)
            : RedirectToRoute("ViewFeed", new { userName = feedViewModel.UserName, feedName = feedViewModel.FeedName });

    public async Task<ActionResult> GetFeed(string userName, string feedName)
    {
        var feed = await feeds.GetAsync(userName, feedName);
        var feedPosts = await posts.GetForFeed(feed);
        var xml = FeedConverter.Create(new Uri($"{Request.Scheme}://{Request.Host.Value}{Request.PathBase.Value}"), feed, feedPosts);
        return Content(xml, "text/xml");
    }

    [HttpPost]
    public async Task<ActionResult> DeletePost([FromServices] PostDeletionUsers usersRequiringKey, [FromServices] PostDeletionKey deletionKey, string userName, string feedName, string title, string key = null)
    {
        if (usersRequiringKey.Users.Any(u => u == userName) && deletionKey.Key != key)
            return RedirectToRoute(nameof(ViewFeed), new { userName, feedName });
        await posts.Delete(userName, feedName, title);
        return RedirectToRoute(nameof(ViewFeed), new { userName, feedName });
    }

    [HttpGet]
    public async Task<ActionResult> EditPost([FromServices] PostDeletionUsers usersRequiringKey, string userName, string feedName, string title)
    {
        ViewBag.NeedsKey = usersRequiringKey.Users.Any(u => u == userName);
        var post = await posts.Get(userName, feedName, title);
        if (post == null)
            return RedirectToRoute("ViewFeed", new { userName, feedName });
        var postViewModel = mapper.Map<PostViewModel>(post);
        ViewBag.IsUpdate = true;
        return View(postViewModel);
    }

    [HttpPost]
    public async Task<ActionResult> EditPost([FromServices] PostDeletionUsers usersRequiringKey, [FromServices] PostDeletionKey editKey, PostViewModel postViewModel, string key = null)
    {
        if (!ModelState.IsValid || usersRequiringKey.Users.Any(u => u == postViewModel.UserName) && editKey.Key != key)
        {
            ViewBag.NeedsKey = usersRequiringKey.Users.Any(u => u == postViewModel.UserName);
            ViewBag.Key = key;
            ViewBag.IsUpdate = true;
            return View(postViewModel);
        }
        var post = await posts.Get(postViewModel.UserName, postViewModel.FeedName, postViewModel.Title);
        if (post == null)
            return RedirectToRoute("ViewFeed", new { userName = postViewModel.UserName, feedName = postViewModel.FeedName });
        _ = mapper.Map(postViewModel, post);
        await posts.Update(post);
        return RedirectToRoute("ViewFeed", new { userName = postViewModel.UserName, feedName = postViewModel.FeedName });
    }
}

src/Recast.WebApp/Views/Shared/_GoogleAnalytics.cshtml
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37678031-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

src/Recast.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Recast &gt; @ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript">
        baseUrl = "@($"{Context.Request.Scheme}://{Context.Request.Host.Value}{Context.Request.PathBase.Value}")
    </script>
    <link rel="stylesheet" href="~/Content/Site.css" />
    <link href="~/Content/themes/base/jquery.ui.core.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery.ui.resizable.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery.ui.selectable.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery.ui.accordion.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery.ui.autocomplete.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery.ui.button.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery.ui.dialog.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery.ui.slider.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery.ui.tabs.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery.ui.datepicker.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery.ui.progressbar.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery.ui.theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
</head>
<body>
    <a href="https://github.com/giggio/Recast/" class="visible-desktop"><img style="position: absolute; top: 0; right: 0; border: 0; z-index: 100000" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"></a>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="@Url.Action("Index", "Home")">Recast</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li>@Html.ActionLink("Go to feed", "GoToFeed", "Feeds")</li>
                        <li>@Html.ActionLink("New feed", "New", "Feeds")</li>
                        <li>@Html.ActionLink("Contribute", "Contribute", "Home")</li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Help
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Support", "Support", "Home")</li>
                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                <li>@Html.ActionLink("About", "About", "Home")</li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <div>
                <p class="visible-desktop">&copy; @DateTime.Now.Year - Recast</p>
                <p class="visible-phone visible-tablet">&copy; @DateTime.Now.Year - Recast - <a href="https://github.com/giggio/Recast/">Fork me on Github</a></p>
            </div>
        </footer>
    </div>
    <!-- /container -->


    <script src="~/Scripts/jquery-1.8.3.js"></script>
    <script src="~/Scripts/jquery-ui-1.9.2.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/startup.min.js"></script>
    @RenderSection("scripts", required: false)
    <partial name="_GoogleAnalytics" />
</body>
</html>
<!-- Podcast icon from Toddle: http://www.toddle.com/ -->